# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.56.11'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]          
          box.vm.provision "shell", inline: <<-SHELL
                    mkdir -p ~root/.ssh
                    cp ~vagrant/.ssh/auth* ~root/.ssh
                    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
                    yum install -y epel-release
                    yum install -y pam_script
                    echo "auth  required  pam_script.so" >> /etc/pam.d/sshd
                    chmod +x /vagrant/pam_script
                    cp /vagrant/pam_script /etc/
                    systemctl restart sshd
                    groupadd admin
                    useradd -G admin user1
                    echo artyomovsky | passwd user1 --stdin
                    useradd user2
                    echo artyomovsky | passwd user2 --stdin
                    echo artyomovsky | passwd root --stdin
                    sed -i "10i account         sufficient      pam_succeed_if.so user = user1 use_uid quiet" /etc/pam.d/su
                    sed -i 13d /etc/pam.d/su
                    sed -i "13i account         required        pam_succeed_if.so user notin root:vagrant:user1" /etc/pam.d/su
                SHELL
          end

      end
  end
end

